services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rhxogml2002!
      MYSQL_DATABASE: commentfilter
      MYSQL_ROOT_HOST: '%'
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql  # ← init.sql
    ports:
      - "3307:3306"
  backend:
    build: .
    env_file: .env
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1

volumes:
  db_data:
